from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Sequence

import pandas as pd

from .base_trainer import Trainer, TrainingConfig, TrainingResult


class YoloV8Trainer(Trainer):
    """
    Process-backed trainer for the YOLOv8 backend.

    This class runs in the control/Optuna environment and deliberately does
    not import Ultralytics. The actual training script is launched using the
    Python interpreter configured at BACKENDS["yolov8"]["python"].
    """

    def __init__(
        self,
        training_script: str | Path | None = None,
    ) -> None:
        if training_script is None:
            training_script = Path(__file__).with_name("yolov8_finetune.py")

        super().__init__(
            backend_name="yolov8",
            training_script=training_script,
        )

    def build_arguments(
        self,
        config: TrainingConfig,
        run_name: str,
    ) -> Sequence[str]:
        """
        Translate the shared TrainingConfig into the CLI expected by
        yolov8_finetune.py.
        """
        args = [
            "--option",
            str(config.option),
            "--data",
            str(Path(config.data).expanduser().resolve()),
            "--weights",
            self._resolve_weight_value(config.weights),
            "--project",
            str(Path(config.project).expanduser().resolve()),
            "--run-name",
            run_name,
            "--epochs",
            str(config.epochs),
            "--imgsz",
            str(config.imgsz),
            "--batch",
            str(config.batch),
            "--lr0",
            str(config.lr0),
            "--lrf",
            str(config.lrf),
            "--optimizer",
            str(config.optimizer),
            "--patience",
            str(config.patience),
            "--save-period",
            str(config.save_period),
            "--seed",
            str(config.seed),
            "--hsv-h",
            str(config.hsv_h),
            "--hsv-s",
            str(config.hsv_s),
            "--hsv-v",
            str(config.hsv_v),
            "--degrees",
            str(config.degrees),
            "--translate",
            str(config.translate),
            "--scale",
            str(config.scale),
            "--shear",
            str(config.shear),
            "--perspective",
            str(config.perspective),
            "--fliplr",
            str(config.fliplr),
            "--flipud",
            str(config.flipud),
            "--device",
            str(config.device),
        ]

        if config.deterministic:
            args.append("--deterministic")

        if config.amp:
            args.append("--amp")

        if config.exist_ok:
            args.append("--exist-ok")

        if config.tag:
            args.extend(["--tag", str(config.tag)])

        if config.extra_args:
            try:
                extra_args_json = json.dumps(config.extra_args)
            except TypeError as exc:
                raise ValueError(
                    "TrainingConfig.extra_args must contain JSON-serializable "
                    "values so they can be passed to the YOLOv8 backend."
                ) from exc

            args.extend(
                [
                    "--extra-args-json",
                    extra_args_json,
                ]
            )

        return args

    def collect_result(
        self,
        config: TrainingConfig,
        run_name: str,
    ) -> TrainingResult:
        """
        Collect the standard files generated by yolov8_finetune.py and parse
        useful validation metrics from Ultralytics' results.csv.
        """
        run_dir = (
            Path(config.project).expanduser().resolve()
            / run_name
        )

        weights_dir = run_dir / "weights"
        best_weights = weights_dir / "best.pt"
        last_weights = weights_dir / "last.pt"

        results_file = run_dir / "results.csv"
        metadata_file = run_dir / "training_metadata.json"

        if not run_dir.is_dir():
            raise FileNotFoundError(
                f"YOLOv8 training completed, but the expected run directory "
                f"was not found: {run_dir}"
            )

        if not best_weights.is_file():
            raise FileNotFoundError(
                f"YOLOv8 training completed, but best.pt was not found: "
                f"{best_weights}"
            )

        metadata: dict[str, Any] = {}
        if metadata_file.is_file():
            metadata = json.loads(
                metadata_file.read_text(encoding="utf-8")
            )

        metrics = self._read_results_metrics(results_file)

        return TrainingResult(
            backend=self.backend_name,
            run_name=run_name,
            run_dir=run_dir,
            best_weights=best_weights,
            last_weights=(
                last_weights
                if last_weights.is_file()
                else None
            ),
            results_file=(
                results_file
                if results_file.is_file()
                else None
            ),
            metadata_file=(
                metadata_file
                if metadata_file.is_file()
                else None
            ),
            metrics=metrics,
            metadata=metadata,
        )

    @staticmethod
    def _resolve_weight_value(
        weights: str | Path,
    ) -> str:
        """
        Preserve Ultralytics model identifiers such as `yolov8x.pt`, while
        converting actual local checkpoint paths to absolute paths.
        """
        value = str(weights)
        expanded = Path(value).expanduser()

        if expanded.is_file():
            return str(expanded.resolve())

        # A value containing directory components is intended to be a local
        # path rather than an Ultralytics model identifier.
        if expanded.parent != Path("."):
            return str(expanded.resolve())

        return value

    @staticmethod
    def _read_results_metrics(
        results_file: Path,
    ) -> dict[str, float]:
        """
        Read useful validation metrics from an Ultralytics results.csv.

        The exact spacing of Ultralytics CSV headers has changed over time, so
        column names are stripped before lookup.
        """
        if not results_file.is_file():
            return {}

        dataframe = pd.read_csv(results_file)
        dataframe.columns = [
            str(column).strip()
            for column in dataframe.columns
        ]

        if dataframe.empty:
            return {}

        metrics: dict[str, float] = {}

        metric_columns = {
            "precision": "metrics/precision(B)",
            "recall": "metrics/recall(B)",
            "map50": "metrics/mAP50(B)",
            "map50_95": "metrics/mAP50-95(B)",
        }

        # Final-epoch values.
        final_row = dataframe.iloc[-1]

        for short_name, column_name in metric_columns.items():
            if column_name in dataframe.columns:
                metrics[f"final_{short_name}"] = float(
                    final_row[column_name]
                )

        # Best values observed during the run.
        for short_name, column_name in metric_columns.items():
            if column_name in dataframe.columns:
                metrics[f"best_{short_name}"] = float(
                    dataframe[column_name].max()
                )

        # For HPO, this is often the most useful single metric.
        map_column = metric_columns["map50_95"]
        if map_column in dataframe.columns:
            best_index = dataframe[map_column].idxmax()

            if "epoch" in dataframe.columns:
                metrics["best_epoch"] = float(
                    dataframe.loc[best_index, "epoch"]
                )
            else:
                metrics["best_epoch"] = float(best_index)

        return metrics